AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  bp-event-driven-architecture-using-event-bridge

  Sample SAM Template for bp-event-driven-architecture-using-event-bridge

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: python3.9
    Handler: app.handler
    Architectures:
      - arm64
    Timeout: 3
    Tracing: Active
    Layers:
      - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension-Arm64:1"

Resources:
  FileReceiverBucket:
    Type: AWS::S3::Bucket
    Properties:
      NotificationConfiguration:
        EventBridgeConfiguration: {}

  OnFileReceiveFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/on_file_receive/
      Events:
        Trigger:
          Type: EventBridgeRule
          Properties:
            Pattern: !Sub |
              {
                "source": ["aws.s3"],
                "detail-type": ["Object Created"],
                "detail": {
                  "bucket": {
                  "name": ["${FileReceiverBucket}"]
                  }
                }
              }
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref FileReceiverBucket
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - events:PutEvents
              Resource: !Sub arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:event-bus/default
  
  OnFileConvertedFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/on_file_converted/
      Events:
        Trigger:
          Type: EventBridgeRule
          Properties:
            Pattern: !Sub |
              {
                "source": ["NFProcessor.file_receiver"],
                "detail-type": ["file-converted"]
              }

  OnFileconvertedErrorQueue:
    Type: AWS::SQS::Queue

  OnFileConvertedErrorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/on_file_converted_error/
      Events:
        Trigger:
          Type: EventBridgeRule
          Properties:
            Pattern: !Sub |
              {
                "source": ["NFProcessor.file_receiver"],
                "detail-type": ["file-converted-error"]
              }
      Environment:
        Variables:
          ERROR_QUEUE_NAME: !Ref OnFileconvertedErrorQueue  
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !Ref OnFileconvertedErrorQueue  
  
  NonSamResources:
    Type: AWS::CloudFormation::Stack
    Properties:
      # The path starts with '../..' as this will be evaluated from the
      # warehouse/build folder, not the warehouse folder.
      TemplateURL: templates/non-sam-resources.yaml

# Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  # HelloWorldFunction:
  #   Description: "Hello World Lambda Function ARN"
  #   Value: !GetAtt HelloWorldFunction.Arn
  # HelloWorldFunctionIamRole:
  #   Description: "Implicit IAM Role created for Hello World function"
  #   Value: !GetAtt HelloWorldFunctionRole.Arn
