openapi: "3.0.1"
info:
  title: "Blogpost API"
paths:
  /filesgenerator:
    post:
      responses:
        default:
          description: "EventBridge response"
      x-amazon-apigateway-integration:
        integrationSubtype: "EventBridge-PutEvents"
        credentials:
          Fn::GetAtt: [FilesGeneratorAPIRole, Arn]
        requestParameters:
          Detail: "$request.body"
          DetailType: "file_generator_request"
          Source: "NFProcessor.api"
        payloadFormatVersion: "1.0"
        type: "aws_proxy"
        connectionType: "INTERNET"